backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Blogginlägg" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Publiceringsdatum", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Bild", name: "image", widget: "image", required: false}
      - {label: "Huvudtext", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Sidor"
    files:
      - file: "site/content/_index.md"
        label: "Förstasidan"
        name: "home"
        fields:
          - {label: Titel, name: title, widget: string}
          - {label: Underrubrik, name: subtitle, widget: string}
          - {label: Bild, name: image, widget: image}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Rubrik", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Rubrik", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Produkter", name: products, widget: list, fields: [
              {label: "Bild", name: "image", widget: "image"}, 
              {label: "Text", name: "text", widget: "string"}, 
              {label: "Text", name: "text2", widget: "string"},
              {label: "Text", name: "text3", widget: "string"},
              {label: "Text", name: "text4", widget: "string"}]}
          - {label: "Material", name: "values", widget: "object", fields: [
              {label: "Rubrik", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "site/content/contact/_index.md"
        label: "Kontaktsidan"
        name: "contact"
        fields:
          - {label: Titel, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Huvudtext, name: body, widget: markdown}
          - label: Kontaktinlägg
            name: contact_entries
            widget: list
            fields:
              - label: Rubrik
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: "site/content/products/_index.md"
        label: "ProdukteSidan"
        name: "products"
        fields:
          - {label: Titel, name: title, widget: string}
          - {label: Bild, name: image, widget: image}
          - {label: Rubrik, name: heading, widget: string}
          - {label: Beskrivning, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Rubrik, name: heading, widget: string}, {label: Beskrivning, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Bild, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Huvud, name: main, widget: object, fields: [{label: Rubrik, name: heading, widget: string}, {label: Beskrivning, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Bild, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Bild, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Bild, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Betyg, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Stor bild, name: full_image, widget: image}
          - {label: Priser, name: pricing, widget: object, fields: [{label: Rubrik, name: heading, widget: string}, {label: Beskrivning, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Pris, name: price, widget: string}, {label: Beskrivning, name: description, widget: string}, {label: Artikel, name: items, widget: list}]}]}
      - file: "site/content/values/_index.md"
        label: "Om Sötvattens Pärlor Page"
        name: "values"
        fields:
          - {label: Titel, name: title, widget: string}
          - {label: Bild, name: image, widget: image}
          - label: Material
            name: values
            widget: list
            fields:
              - {label: Titel, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Bild, name: imageUrl, widget: image}
